---

mysql_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61383635386634616165636330376534303431336662653761313935613133323663336335646666
          6336383562373561623462306632303832633964613234370a346439383336633533383364303936
          62333663343461383265626439366166663732666264316435373631376362613736643134326663
          3934653737316536350a346663393362626332343331393935653935376638656561653732626536
          3765


mysql_user_name: 'wordpress'
mysql_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34613866363662363837366164356163326432633638663261613135303566316537663436626564
          6630323361663361613564346466353261636136666562310a646339383666623531643038613038
          61623535316131373166316666626430303161633633366661653130363362643939626437353534
          3464373234313437330a653732643732363662303363313133386130363762383162653562366330
          61646232613335313538363864366334646333623064373961623433343166663762

mysql_user_privileges: 'wordpress.*:ALL'

nginx_document_root: '/opt/wordpress'
nginx_index_files: 'index.php index.html'
nginx_server_name: '{{ ansible_default_ipv4.address }}'
nginx_php_fpm_sock_path: '/var/run/php/{{ php_version }}-fpm.sock'

wordpress_mysql_db_user: '{{ mysql_user_name }}'
wordpress_mysql_db_password: '{{ mysql_user_password }}'
wordpress_mysql_login_user: 'root'
wordpress_mysql_login_password: '{{ mysql_root_password }}'