---
mysql_version: '8.0.23'

mysql_unix_socket_path: '/var/run/mysqld/mysqld.sock'

mysql_root_password: 'secret'

mysql_user_name: 'user'
mysql_user_password: 'secret'
mysql_user_privileges: '*.*:ALL'

# defaults file for mysql
